define({
	"navigation": "Baker",
	"appid": "Bundle Identifier für die App",
	"apptype": "App Typ",
	"orientation": "Gerät Ausrichtung",
	"orPortrait": "Portrait",
	"orUpsidedown": "Auf den Kopf gestellt",
	"orLandscapeleft": "Landschaft links",
	"orLandscaperight": "Landschaft rechts",
	"uiconstants": "Baker UI Konstanten",
	"bakerColorsetCoverBg": "Cover Hintergrundfarbe",
	"bakerColorsetTitleColor": "Titelfarbe",
	"bakerColorsetInfoColor": "Infofarbe",
	"bakerColorsetPriceColor": "Preisfarbe",
	"bakerColorsetActionButtonBg": "Action Button Hintergrundfarbe",
	"bakerColorsetActionButtonColor": "Action Button Farbe",
	"bakerColorsetArchiveButtonBg": "Archiv Button Hintergrundfarbe",
	"bakerColorsetArchiveButtonColor": "Archive Button Farbe",
	"bakerColorsetLoadingLabelColor": "Loading Label Farbe",
	"bakerColorsetLoadingSpinnerColor" :"Loading Spinner Farbe",
	"bakerColorsetProgressbarTintColor": "Progressbar Tint Farbe",
	"download": "App downloaden",
	"standalone": "Standalone App",
	"newsstand": "Newsstand App",
	"paid": "Newsstand App mit Bezahlung"
});