define({
	"CLOSE" : "Close",
	"SHELFNAVIGATIONTITLE" : "Baker Shelf",
	"PRODUCTSREQUESTFAILEDTITLE" : "Es konnte keine Verbindung mit dem App Store hergestellt werden",
	"INFOBUTTONTEXT" : "Info",
	"SUBSCRIBEBUTTONTEXT" : "Abbonieren",
	"SUBSCRIBEBUTTONDISABLEDTEXT" : "Abboniere...",
	"SUBSCRIBEBUTTONSUBSCRIBEDTEXT" : "Abboniert",
	"SUBSCRIPTIONSSHEETFREE" : "Gratis Abonieren",
	"SUBSCRIPTIONSSHEETRESTORE" : "Wiederherstellen der Käufe",
	"SUBSCRIPTIONSSHEETGENERIC" : "Abbonier Einstellungen",
	"SUBSCRIPTIONSSHEETSUBSCRIBED" : "Du bist Abonnent",
	"SUBSCRIPTIONSSHEETNOTSUBSCRIBED" : "Du bist kein Abonnent",
	"SUBSCRIPTIONSUCCESSFULTITLE" : "Abbonieren erfolgreich abgeschlossen",
	"SUBSCRIPTIONSUCCESSFULMESSAGE" : "Du hast es Abboniert",
	"SUBSCRIPTIONFAILEDTITLE" : "Abbonieren fehlgeschlagen",
	"ISSUEPURCHASESUCCESSFULTITLE" : "Bezahlung erfolgreich",
	"ISSUEPURCHASESUCCESSFULMESSAGE" : "Du hast %@ bezahlt",
	"ISSUEPURCHASEFAILEDTITLE" : "Bezahlung fehlgeschlagen",
	"RESTOREFAILEDTITLE" : "Wiederherstellung fehlgeschlagen",
	"RESTOREDISSUENOTRECOGNISEDTITLE" : "Einige Ausgaben konnte nicht wiederhergestellt werden",
	"RESTOREDISSUENOTRECOGNISEDMESSAGE" : "Die folgenden Produkt IDs sind nicht definiert, darum konnten die folgende Ausgabe nicht wiederhergestellt werden:\n%@.\n\nBitte kontaktieren sie den Herausgeber",
	"DOWNLOADFAILEDTITLE" : "Download fehlgeschlagen",
	"DOWNLOADFAILEDMESSAGE" : "Ausgabe konnte nicht Heruntergeladen werden",
	"UNZIPFAILEDTITLE" : "Fehler beim öffnen",
	"UNZIPFAILEDMESSAGE" : "Ausgabe konnte nicht geöffnet werden",
	"INTERNETCONNECTIONUNAVAILABLETITLE" : "Keine Internetverbindung!",
	"INTERNETCONNECTIONUNAVAILABLEMESSAGE" : "Keine Internetverbindung! Um den vollen Funktionsumfang nützen zu können benötigen sie eine Internet Verbindung",
	"INTERNETCONNECTIONUNAVAILABLECLOSE" : "OK",
	"ACTIONREMOTETEXT" : "DOWNLOAD",
	"ACTIONDOWNLOADEDTEXT" : "LESEN",
	"ACTIONBUYTEXT" : "KAUFEN",
	"ARCHIVETEXT" : "ARCHIVIERE",
	"CONNECTINGTEXT" : "VERBINDE...",
	"DOWNLOADINGTEXT" : "DOWNLOADING ...",
	"OPENINGTEXT" : "Lade...",
	"BUYINGTEXT" : "KAUFE...",
	"RETRIEVINGTEXT" : "AKTUALISIERE PREIS...",
	"FREETEXT" : "FREI",
	"PURCHASEDTEXT" : "GEKAUFT",
	"ARCHIVEALERTTITLE" : "Bist du sicher das du diese Ausgabe Archivieren willst?",
	"ARCHIVEALERTMESSAGE" : "Diese Ausgabe wird von diesem Gerät entfernt. Du hast aber die möglichkeit es jederzeit wieder gratis herunterzuladen",
	"ARCHIVEALERTBUTTONCANCEL" : "Cancel",
	"ARCHIVEALERTBUTTONOK" : "Archiv",
	"MAILTOALERTTITLE" : "Fehler",
	"MAILTOALERTMESSAGE" : "Dein Gerät kann keine Email's senden!",
	"MAILTOALERTCLOSE" : "OK",
	"WEBMODALFAILUREMESSAGE" : "Konnte keine Verbindung aufbauen",
	"WEBMODALCLOSEBUTTONTEXT" : "Zurück",
	"TRANSACTIONRECORDINGFAILEDTITLE" : "Kauf konnte vom Remoteerver nicht bestätigt werden",
	"TRANSACTIONRECORDINGFAILEDMESSAGE" : "Der Vorgang wird wiederholt, bis er erfolgreich ist",
	"ISSUEOPENINGFAILEDTITLE" : "Konnte die Ausgabe leider nicht öffnen",
	"ISSUEOPENINGFAILEDMESSAGE" : "Error beim öffnen der Ausgabe. Bitte wiederhole den Download oder kontaktieren den Herausgeber."
});