define({
	"navigation": "Magazine",
	"layouts": "Vorlagen",
	"print": "Druck Pdf's aktivieren",
	"details": "Magazin Details",
	"title": "Titel",
	"author": "Autor",
	"publish": "Publish",
	"unpublish": "Unpublish",
	"downloadPdf": "Download Druck Pdf",
	"impressum": "Impressum",
	"editorial": "Editorial",
	"product_id": "Produkt ID",
    "info": "Info",
	"papersize": "Papierformat auswählen (Druck)",
	"orientation": "Paperausrichtung auswählen (Druck)",
	"newMagazine": "hat eines Neues Magazine erstellt",
    "updateMagazine": "hat ein Magazine aktualisiert",
    "emptyMessage": "Das Magazine existiert nicht mehr",
    "deleteMagazine": "hat ein Magazine gelöscht"
});