define({
	"pageHeadline": "Seiten",
	"cover": "Titelseite",
	"back": "Rückseite",
	"downloadHpub": "Download hpub",
	"index": "Inhaltsverzeichnis",
	"editorial": "Editorial",
	"preview": "Voransicht",
    "addPage": "Seite hinzufügen",
	"navigation": "Magazine",
	"layouts": "Vorlagen",
	"print": "Druck Pdf's aktivieren",
	"details": "Magazin Details",
	"title": "Titel",
	"author": "Autor",
	"publish": "Publish",
	"unpublish": "Unpublish",
	"downloadPdf": "Druck PDF",
	"impressum": "Impressum",
	"editorial": "Editorial",
	"product_id": "Produkt ID",
    "info": "Info",
	"papersize": "Papierformat auswählen (Druck)",
	"orientation": "Paperausrichtung auswählen (Druck)",
	"newMagazine": "hat eines Neues Magazine erstellt",
    "updateMagazine": "hat ein Magazine aktualisiert",
    "emptyMessage": "Das Magazine existiert nicht mehr",
    "deleteMagazine": "hat ein Magazine gelöscht"
});