define({
	"root": {
		"CLOSE" : "Close",
		"SHELFNAVIGATIONTITLE" : "Baker Shelf",
		"PRODUCTSREQUESTFAILEDTITLE" : "Failure connecting to the App Store",
		"INFOBUTTONTEXT" : "Info",
		"SUBSCRIBEBUTTONTEXT" : "Subscribe",
		"SUBSCRIBEBUTTONDISABLEDTEXT" : "Subscribing...",
		"SUBSCRIBEBUTTONSUBSCRIBEDTEXT" : "Subscribed",
		"SUBSCRIPTIONSSHEETFREE" : "Subscribe for free",
		"SUBSCRIPTIONSSHEETRESTORE" : "Restore purchases",
		"SUBSCRIPTIONSSHEETGENERIC" : "Subscription options",
		"SUBSCRIPTIONSSHEETSUBSCRIBED" : "You are subscribed",
		"SUBSCRIPTIONSSHEETNOTSUBSCRIBED" : "You are not subscribed",
		"SUBSCRIPTIONSUCCESSFULTITLE" : "Subscribed successfully",
		"SUBSCRIPTIONSUCCESSFULMESSAGE" : "You have successfully subscribed",
		"SUBSCRIPTIONFAILEDTITLE" : "Subscription failure",
		"ISSUEPURCHASESUCCESSFULTITLE" : "Purchase successful",
		"ISSUEPURCHASESUCCESSFULMESSAGE" : "You have successfully purchased %@",
		"ISSUEPURCHASEFAILEDTITLE" : "Purchase failure",
		"RESTOREFAILEDTITLE" : "Restore failure",
		"RESTOREDISSUENOTRECOGNISEDTITLE" : "Some issues could not be restored",
		"RESTOREDISSUENOTRECOGNISEDMESSAGE" : "The following product IDs are not defined and the corresponding issues could not be restored:\n%@.\n\nContact the app creator for more info.",
		"DOWNLOADFAILEDTITLE" : "Download failed",
		"DOWNLOADFAILEDMESSAGE" : "The issue could not be downloaded",
		"UNZIPFAILEDTITLE" : "Opening failed",
		"UNZIPFAILEDMESSAGE" : "The issue could not be opened",
		"INTERNETCONNECTIONUNAVAILABLETITLE" : "No Internet Connection",
		"INTERNETCONNECTIONUNAVAILABLEMESSAGE" : "An Internet connection is unavailable. Some features of this application require an active connection.",
		"INTERNETCONNECTIONUNAVAILABLECLOSE" : "OK",
		"ACTIONREMOTETEXT" : "DOWNLOAD",
		"ACTIONDOWNLOADEDTEXT" : "READ",
		"ACTIONBUYTEXT" : "BUY",
		"ARCHIVETEXT" : "ARCHIVE",
		"CONNECTINGTEXT" : "CONNECTING...",
		"DOWNLOADINGTEXT" : "DOWNLOADING ...",
		"OPENINGTEXT" : "Loading...",
		"BUYINGTEXT" : "BUYING...",
		"RETRIEVINGTEXT" : "UPDATING PRICE...",
		"FREETEXT" : "FREE",
		"PURCHASEDTEXT" : "PURCHASED",
		"ARCHIVEALERTTITLE" : "Are you sure you want to archive this issue?",
		"ARCHIVEALERTMESSAGE" : "This issue will be removed from your device. You may download it at anytime for free.",
		"ARCHIVEALERTBUTTONCANCEL" : "Cancel",
		"ARCHIVEALERTBUTTONOK" : "Archive",
		"MAILTOALERTTITLE" : "Failure",
		"MAILTOALERTMESSAGE" : "Your device doesn't support the sending of emails!",
		"MAILTOALERTCLOSE" : "OK",
		"WEBMODALFAILUREMESSAGE" : "Unable to connect.",
		"WEBMODALCLOSEBUTTONTEXT" : "Back",
		"TRANSACTIONRECORDINGFAILEDTITLE" : "Could not confirm purchase with remote server",
		"TRANSACTIONRECORDINGFAILEDMESSAGE" : "The operation will be retried until it is successful",
		"ISSUEOPENINGFAILEDTITLE" : "Could not open issue",
		"ISSUEOPENINGFAILEDMESSAGE" : "There was an error opening this issue. Try downloading it again or contact the publisher.",
	},
	"de": true

});