define({
    "root": {
    	"navigation": "Magazines",
    	"cover": "Cover",
    	"back": "Back",
    	"downloadHpub": "Download hpub",
    	"index": "Index",
    	"editorial": "Editorial",
    	"preview": "Preview",
    	"pageHeadline": "Pages",
    	"addPage": "Add Page",
    	"layouts": "Layouts",
    	"theme": "Theme",
    	"print": "Enable Print PDF",
    	"publish": "Publish",
    	"unpublish": "Unpublish",
    	"downloadPdf": "Download Print Pdf",
    	"details": "Magazine details",
        "title": "Title",
        "author": "Author",
        "article": "Article",
        "product_id": "Product ID",
        "info": "Info",
        "impressum": "Impressum",
        "editorial": "Editorial",
        "papersize": "Select Papersize (Print)",
        "orientation": "Select Orientation (Print)",
       	"fileDescription": "Use 'cover' and 'back' templates keys",
        "newMagazine": "created new magazine",
        "updateMagazine": "updated magazine",
        "emptyMessage": "The magazine does not exist anymore",
        "deleteMagazine": "deleted magazine"
    },
    "de": true
});