#ifndef Baker_UIConstants_h
#define Baker_UIConstants_h
	#define ISSUES_COVER_BACKGROUND_COLOR @"#ffffff"
	#define ISSUES_TITLE_COLOR @"#000000"
	#define ISSUES_INFO_COLOR @"#929292"
	#define ISSUES_PRICE_COLOR @"#bc242a"
	#define ISSUES_ACTION_BUTTON_BACKGROUND_COLOR @"#bc242a"
	#define ISSUES_ACTION_BUTTON_COLOR @"#ffffff"
	#define ISSUES_ARCHIVE_BUTTON_COLOR @"#bc242a"
	#define ISSUES_ARCHIVE_BUTTON_BACKGROUND_COLOR @"#ffffff"
	#define ISSUES_LOADING_LABEL_COLOR @"#bc242a"
	#define ISS0UES_LOADING_SPINNER_COLOR @"#929292"
	#define ISSUES_PROGRESSBAR_TINT_COLOR @"#bc242a"
#endif